module.exports = [
  {
    VOCName: "Pentanal",
    Concentration: "5.9 ppb",
    CancerType: "Lung",
    Gradient: "up",
  },
  {
    VOCName: "Hexanal",
    Concentration: "6-12 ppb",
    CancerType: "Lung",
    Gradient: "down",
  },
  {
    VOCName: "Octanal",
    Concentration: "3-7 ppb",
    CancerType: "Lung",
    Gradient: "up",
  },
  {
    VOCName: "Nonanal",
    Concentration: "8.333 ppb",
    CancerType: "Lung",
    Gradient: "up",
  },
  {
    VOCName: "Butan-1-ol",
    Concentration: "0.367-3  ppb",
    CancerType: "Lung",
    Gradient: "up",
  },
  {
    VOCName: "3-Hydroxybutan-2-one",
    Concentration: "0.00381 ppb",
    CancerType: "Lung",
    Gradient: "up",
  },
  {
    VOCName: "2-Butanone",
    Concentration: "3.8-38.8 ppb",
    CancerType: "Lung",
    Gradient: "down",
  },
  {
    VOCName: "Isoprene",
    Concentration: "19.2-295.5 ppb",
    CancerType: "Lung",
    Gradient: "up",
  },
  {
    VOCName: "Ethylbenzene",
    Concentration: "19.6 ppb",
    CancerType: "Lung",
    Gradient: "up",
  },
  {
    VOCName: "Acetone",
    Concentration: "112-2653.3 ppb",
    CancerType: "Lung",
    Gradient: "up",
  },
  {
    VOCName: "2-Pentanone",
    Concentration: "7.5 ppb",
    CancerType: "Lung",
    Gradient: "up",
  },
  {
    VOCName: "Benzene",
    Concentration: "4.6-130 ppb",
    CancerType: "Lung",
    Gradient: "up",
  },
  {
    VOCName: "2-Methyl propanal",
    Concentration: "6.84 - 94.36 ppb",
    CancerType: "Lung",
    Gradient: "down",
  },
  {
    VOCName: "n-Pentane",
    Concentration: "3.7-116.7 ppb",
    CancerType: "Lung",
    Gradient: "up",
  },
  {
    VOCName: "Benzaldehyde",
    Concentration: "9.9 - 86.9 ppb",
    CancerType: "Lung",
    Gradient: "down",
  },
  {
    VOCName: "Dimethyl Sulfide",
    Concentration: "6.3-18.5 ppb",
    CancerType: "Lung",
    Gradient: "down",
  },
  {
    VOCName: "4-Methyl Octane",
    Concentration: "2.2 - 4.5 ppb",
    CancerType: "Lung",
    Gradient: "up",
  },
  {
    VOCName: "Acetaldehyde",
    Concentration: "4.1 - 272.7 ppb",
    CancerType: "Lung",
    Gradient: "up",
  },
  {
    VOCName: "Ethanol",
    Concentration: "12.8-1520.1  ppb",
    CancerType: "Lung",
    Gradient: "up",
  },
  {
    VOCName: "Acetonitrile",
    Concentration: "7.1-794.1 ppb",
    CancerType: "Lung",
    Gradient: "down",
  },
  {
    VOCName: "Carbon disulphide",
    Concentration: "5-19 ppb",
    CancerType: "Lung",
    Gradient: "down",
  },
  {
    VOCName: "2-Methyl pentane",
    Concentration: "8.5 ppb",
    CancerType: "Lung",
    Gradient: "up",
  },
  {
    VOCName: "3-Methyl pentane",
    Concentration: "6.6 ppb",
    CancerType: "Lung",
    Gradient: "up",
  },
  {
    VOCName: "p-xylene",
    Concentration: "10 ppb",
    CancerType: "Lung",
    Gradient: "up",
  },
  {
    VOCName: "o-xylene",
    Concentration: "22.1 ppb",
    CancerType: "Lung",
    Gradient: "up",
  },
  {
    VOCName: "4-Methyl octane",
    Concentration: "3.1 ppb",
    CancerType: "Lung",
    Gradient: "up",
  },
  {
    VOCName: "Allylmethyl sulphide",
    Concentration: "9.2 - 80.5 ppb",
    CancerType: "Lung",
    Gradient: "down",
  },
  {
    VOCName: "Hexanal",
    Concentration: "4.5 ppb",
    CancerType: "Lung",
    Gradient: "down",
  },
  {
    VOCName: "2-Methyl heptane",
    Concentration: "3.6 ppb",
    CancerType: "Lung",
    Gradient: "up",
  },
  {
    VOCName: "Styrene",
    Concentration: "4.4 - 76.8  ppb",
    CancerType: "Lung",
    Gradient: "up",
  },
  {
    VOCName: "Butyl acetate",
    Concentration: "3.8 - 33.5 ppb",
    CancerType: "Lung",
    Gradient: "down",
  },
  {
    VOCName: "Propanal",
    Concentration: "5.5-33.8 ppb",
    CancerType: "Lung",
    Gradient: "up",
  },
  {
    VOCName: "3-Methyl butanal",
    Concentration: "1.32 - 2.55 ppb",
    CancerType: "Lung",
    Gradient: "down",
  },
  {
    VOCName: "2- Methyl butane",
    Concentration: "7.4 - 74.5 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "3-Butyn-2-ol",
    Concentration: "51.5 - 337.8  ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "Y- Butyrolacetone",
    Concentration: "13.1 - 114.8 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "2-Methyl-1-butene",
    Concentration: "2.1-58.4 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "2-Methyl-2-butene",
    Concentration: "9.5-83.4 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "2,3-Butenedione",
    Concentration: "5.8 - 72.4 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "Dimethyl ether",
    Concentration: "11.2 - 105 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "Pyridine",
    Concentration: "12.5 - 109.2  ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "2-Methyl-1-pentene",
    Concentration: "4.1 - 35.8 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "Limonene",
    Concentration: "6.2 - 54.6 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "3-Methyl furan",
    Concentration: "7.2 - 58.3 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "N,N-dimethyl acetamide",
    Concentration: "10.9 - 95.0 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "1,3 -Cyclohexadiene",
    Concentration: "10.6-92.6 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "P-cymene",
    Concentration: "6.5 - 56.6 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "N,N-dimethyl formamide",
    Concentration: "21.9 - 67.2 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "Eucalyptol",
    Concentration: "6.1 - 52.7 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "2-Propanol",
    Concentration: "8.7 - 989.2 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "Isopropanol",
    Concentration: "3.32 - 19.19 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "Heptane",
    Concentration: "3.4  ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "Butane",
    Concentration: "6.1-421.3 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "Furan",
    Concentration: "3.1-7.0 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "2-Methyl Furan",
    Concentration: "5.5-14.8 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "3-Buten-2-one",
    Concentration: "5.5-8.2 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "Ethyl acetate",
    Concentration: "6.6 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "Hexane",
    Concentration: "33.6 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "2,5- Dimethyl furan",
    Concentration: "6.1-49.2 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "Toluene",
    Concentration: "12.9 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "Heptane",
    Concentration: "3.4 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "Propane",
    Concentration: "3.19-9.74 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "2-Propenal",
    Concentration: "6.84 - 94.36 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "1,4-Pentadiene",
    Concentration: "9.8-85.5 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "3-Hydroxy-2-butanone",
    Concentration: "1.3-7.7 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "2-Hydroxyacetaldehyde",
    Concentration: "3-10.5 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "1-Propanol",
    Concentration: "5.4-473.3 ppb",
    CancerType: "Lung",
  },
  {
    VOCName: "3-Methylhexane",
    Concentration: "0.55 μg/m³",
    CancerType: "Breast",
    Gradient: "down",
  },
  {
    VOCName: "Dec-1-ene",
    Concentration: "0.125 μg/m³",
    CancerType: "Breast",
    Gradient: "down",
  },
  {
    VOCName: "Caryophyllene",
    Concentration: "0.05 μg/m³",
    CancerType: "Breast",
    Gradient: "down",
  },
  {
    VOCName: "Naphthalene",
    Concentration: "0.05 μg/m³",
    CancerType: "Breast",
    Gradient: "down",
  },
  {
    VOCName: "Trichloroethene",
    Concentration: "0.05 μg/m³",
    CancerType: "Breast",
    Gradient: "up",
  },
  {
    VOCName: "Hexanal",
    Concentration: "10.32 ppb",
    CancerType: "Breast",
    Gradient: "up",
  },
  {
    VOCName: "Heptanal",
    Concentration: "9.98 ppb",
    CancerType: "Breast",
    Gradient: "up",
  },
  {
    VOCName: "Octanal",
    Concentration: "12.9 ppb",
    CancerType: "Breast",
    Gradient: "up",
  },
  {
    VOCName: "Nonanal",
    Concentration: "23.14 ppb",
    CancerType: "Breast",
    Gradient: "up",
  },
];
